spring:
  application:
    name: "com-chrdw-push"
  kafka:
    # 指定kafka 代理地址，可以多个
    bootstrap-servers:
      - kafka1:9092
#      - kafka2:9092
#      - kafka3:9093
    # =============== 生产者配置=============
    producer:
      retries: 1
      batch-size: 10
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: price-event
    # ===============消费者配置===============
    consumer:
      group-id: price-push
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.chrdw.push.service.model


server:
  tomcat:
    basedir: .
    max-threads: 10
    accesslog:
      enabled: true
    max-connections: 10
    accept-count: 10
  port: 8080


config:
# ========AppConfig============
  appconfig:
    consumeEventThreadCnt: 1
    produceEventThreadCnt: 2
    pushexecutor:
      corePoolSize: 10
      maxPoolSize: 10
    kafkaTopicId: price-event
    kafkaConsumerPollBatchSize: 10
    kafkaConsumerPollTimeOut: 5
    pushTimeout: 5000

# ========AppConfig============

# ========CustomConfig============


# ========CustomConfig============

