version: '2'
services:
    kafka1:
        image: wurstmeister/kafka
        restart: on-failure
        hostname: kafka1
        container_name: kafka1
        ports:
          - "9091:9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka1
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - /home/chrdw/kfkcluster/kafka1/logs:/logs
        external_links:
          - zk1
          - zk2
          - zk3
    kafka2:
        image: wurstmeister/kafka
        restart: on-failure
        hostname: kafka2
        container_name: kafka2
        ports:
          - "9092:9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka2
          KAFKA_ADVERTISED_PORT: 9092 
          KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - /home/chrdw/kfkcluster/kafka2/logs:/logs
        external_links: 
          - zk1
          - zk2
          - zk3
    kafka3:
        image: wurstmeister/kafka
        restart: on-failure
        hostname: kafka3
        container_name: kafka3
        ports:
          - "9093:9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka3
          KAFKA_ADVERTISED_PORT: 9092 
          KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - /home/chrdw/kfkcluster/kafka3/logs:/logs
        external_links: 
          - zk1
          - zk2
          - zk3

