version: '2'
services:
  zk1:
    image: zookeeper:3.4
    restart: always
    hostname: zk1
    container_name: zk1
    ports:
      - "2181:2181"
    volumes:
      - /home/chrdw/zkcluster/zk1/data:/data
      - /home/chrdw/zkcluster/zk1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      zkkfk:
        ipv4_address: 172.19.1.10
  zk2:
    image: zookeeper:3.4
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    volumes:
      - /home/chrdw/zkcluster/zk2/data:/data
      - /home/chrdw/zkcluster/zk2/datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    depends_on:
      - zk1
    networks:
      zkkfk:
        ipv4_address: 172.19.1.11
  zk3:
    image: zookeeper:3.4
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    volumes:
      - /home/chrdw/zkcluster/zk3/data:/data
      - /home/chrdw/zkcluster/zk3/datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    depends_on:
      - zk1
      - zk2
    networks:
      zkkfk:
        ipv4_address: 172.19.1.12
  kafka1:
    image: wurstmeister/kafka:2.11-2.0.0
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    volumes:
      - /home/chrdw/kfkcluster/kafka1/logs:/logs
    external_links:
      - zk1
      - zk2
      - zk3
    depends_on:
      - zk1
      - zk2
      - zk3
    networks:
      zkkfk:
        ipv4_address: 172.19.1.13
  kafka2:
    image: wurstmeister/kafka:2.11-2.0.0
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    volumes:
      - /home/chrdw/kfkcluster/kafka2/logs:/logs
    external_links:
      - zk1
      - zk2
      - zk3
    depends_on:
      - zk1
      - zk2
      - zk3
    networks:
      zkkfk:
        ipv4_address: 172.19.1.14
  kafka3:
    image: wurstmeister/kafka:2.11-2.0.0
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    volumes:
      - /home/chrdw/kfkcluster/kafka3/logs:/logs
    external_links:
      - zk1
      - zk2
      - zk3
    depends_on:
      - zk1
      - zk2
      - zk3
    networks:
      zkkfk:
        ipv4_address: 172.19.1.15
networks:
  zkkfk:
    external:
      name: zkkfk
