version: '2'
services:
  zk1:
    image: zookeeper:3.4.14
    restart: always
    hostname: zk1
    container_name: zk1
    ports:
      - "2181:2181"
    volumes:
      - /home/chrdw/zkcluster/zk1/data:/data
      - /home/chrdw/zkcluster/zk1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888
    networks:
      zkkfk:
        ipv4_address: 172.19.1.10
  kafka1:
    image: wurstmeister/kafka:2.11-2.0.0
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
    volumes:
      - /home/chrdw/kfkcluster/kafka1/logs:/logs
    external_links:
      - zk1
    depends_on:
      - zk1
    networks:
      zkkfk:
        ipv4_address: 172.19.1.13
networks:
  zkkfk:
    external:
      name: zkkfk
