version: '2'
services:
  zk1:
    image: zookeeper:3.4.14
    restart: always
    hostname: zk1
    container_name: zk1
    ports:
      - "2181:2181"
    volumes:
      - /home/chrdw/zkcluster/zk1/data:/data
      - /home/chrdw/zkcluster/zk1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    external_links:
      - zk1
      - zk2
      - zk3
  zk2:
    image: zookeeper:3.4.14
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    volumes:
      - /home/chrdw/zkcluster/zk2/data:/data
      - /home/chrdw/zkcluster/zk2/datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    external_links:
      - zk1
      - zk2
      - zk3
    depends_on:
      - zk1
  zk3:
    image: zookeeper:3.4.14
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    volumes:
      - /home/chrdw/zkcluster/zk3/data:/data
      - /home/chrdw/zkcluster/zk3/datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    external_links:
      - zk1
      - zk2
      - zk3
    depends_on:
      - zk1
      - zk2
  kafka1:
    image: wurstmeister/kafka:2.11-2.0.0
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    volumes:
      - /home/chrdw/kfkcluster/kafka1/logs:/logs
    external_links:
      - zk1
      - zk2
      - zk3
    depends_on:
      - zk1
      - zk2
      - zk3
