version: '2'
services:
    zk1:
        image: zookeeper:3.4
        restart: on-failure
        hostname: zk1
        container_name: zk1
        ports:
          - "2181:2181"
        volumes: 
          - /home/chrdw/zkcluster/zk1/data:/data
          - /home/chrdw/zkcluster/zk1/datalog:/datalog
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    zk2:
        image: zookeeper:3.4
        restart: on-failure
        container_name: zk2
        ports:
          - "2182:2181"
        volumes: 
          - /home/chrdw/zkcluster/zk2/data:/data
          - /home/chrdw/zkcluster/zk2/datalog:/datalog
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    zk3:
        image: zookeeper:3.4
        restart: on-failure
        container_name: zk3
        ports:
          - "2183:2181"
        volumes: 
        - /home/chrdw/zkcluster/zk3/data:/data
        - /home/chrdw/zkcluster/zk3/datalog:/datalog
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

